### ISSUE TITLE
Create a troubleshooting section

### ISSUE THREAD

**Issue by HumbleDeer** [VzBoT3D/docs#56]
Create a section on the website regarding troubleshooting printer issues. This should apply to both the Vz330 as well as the Vz235, since they're fairly similar. 

Example / Sample questions:

* My prints are mirrored
* My printer homes the wrong way / in the wrong direction
* 

This idea stems from the most prevalent issues in the VzBot server being the ones that are repeating/reocurring.

**Comment by DerDackel** [comment]
A general "Initial startup" checklist would make sense and could catch a lot of these. This could probably done in a single common section for all VzBot variants, with some optional sections for AWD.

Stuff like
* Check endstops
* Test homing -> Wiring guidance if the printhead doesn't move in the right direction
* Check fans/pump
* etc.

**Comment by HumbleDeer** [comment]
Kdb often references the voron guide for first starts. Do we take inspiration from that?
