### ISSUE TITLE
Touch on DSI touchscreens may not work with Raspberry Pis due to kernel driver issue

### ISSUE THREAD

**Issue by DerDackel** [VzBoT3D/docs#69]
Touch on DSI-based screens, like Mellow's LCD included in their ktis might not work due to underlying issues with the Raspberry Pi's KMS driver.

Workaround is described by the KlipperScreen team here: https://klipperscreen.readthedocs.io/en/latest/Troubleshooting/Touch_issues/

This should probably be added as an info box for Raspi users in the Firmware Setup section. Other SBCs shouldn't be affected as this is a Raspi-specific driver.

Note: Verified this myself, but had to switch drivers exactly the other way round. There are various such problems listed in Raspberry's Github.

Tested on an RPi 4B 8GB running a fresh MainsailOS

```
pi@simonsays:~ $ uname -a
Linux simonsays 6.1.21-v8+ #1642 SMP PREEMPT Mon Apr  3 17:24:16 BST 2023 aarch64 GNU/Linux
```

**Comment by HumbleDeer** [comment]
Affected pages: 

- https://docs.vzbot.org/vz330_mellow/electronics/Firmware
- https://docs.vzbot.org/vz235_printed/electronics/Firmware
- https://docs.vzbot.org/vz235_mellow/electronics/Firmware
