### ISSUE TITLE
printer.cfg replacement in the docs?

### ISSUE THREAD

**Issue by 1980alexGS** [VzBoT3D/docs#86]
Hello - can the file here on Github named 330AWD-printer.cfg replace the printer.cfg linked at https://docs.vzbot.org/vz330_mellow/electronics/Printer_Config - the link there seems to be broken? Thanks

**Comment by EduardoMDSousa** [comment]
Yes 330awd is the printer.cfg just rename it

**Comment by 1980alexGS** [comment]
Thanks Eduardo - link on that page is broken - it tries to go to https://docs.vzbot.org/assets%5Cimages%5Cmanual%5Cvz330_mellow%5Celectronics%5CPrinter_config%5Cprinter.cfg

**Comment by EduardoMDSousa** [comment]
Yes i see , the page admin need to Change the file name, becase was Changed. 👍

**Comment by HumbleDeer** [comment]
Issue was fixed in #76 (and sub-pieces were already comitted)
